name: easy_vat_v2
description: "Easy Vat - Loyal Accounting Services."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  auto_route: ^9.3.0+1
  shared_preferences: ^2.5.2
  freezed: ^2.5.8
  flutter_svg: ^2.0.17
  flex_color_scheme: ^8.1.1
  intl: ^0.19.0
  flutter_slidable: ^4.0.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.4
  equatable: ^2.0.7
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  hive_ce: ^2.10.1
  pinput: ^5.0.1
  firebase_core: ^3.12.1
  mobile_scanner: ^6.0.7
  fl_chart: ^1.0.0
  shimmer: ^3.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1  
  build_runner: ^2.4.15
  flutter_gen: ^5.9.0
  flutter_native_splash: ^2.4.5
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/images/Logo.png"
  
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/Logo.png
  android: true
  ios: true
  web: true
  android_gravity: center
  ios_content_mode: scaleAspectFit
  web_image_mode: contain
  fullscreen: false

# swagger_parser:
#   schema_path: assets/schemas/easy_vat_swagger.json
#   output_directory: lib/api

flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/images/
    - assets/icons/
    - assets/icons/dark/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
