name: easy_vat_v2
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  dio: ^5.8.0+1
  flutter_screenutil: ^5.9.3
  auto_route: ^9.3.0+1
  shared_preferences: ^2.5.2
  freezed: ^2.5.8
  flutter_svg: ^2.0.17
  flex_color_scheme: ^8.1.1
  intl: ^0.19.0
  flutter_slidable: ^4.0.0
  pretty_dio_logger: ^1.4.0
  dartz: ^0.10.1
  freezed_annotation: ^2.4.4
  json_serializable: ^6.9.4
  equatable: ^2.0.7
  uuid: ^4.5.1
  fluttertoast: ^8.2.12
  hive_ce: ^2.10.1
  pinput: ^5.0.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  auto_route_generator: ^9.3.1  
  build_runner: ^2.4.15
  flutter_gen: ^5.9.0


flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/images/
    - assets/icons/
    - assets/icons/dark/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Thin.ttf
          weight: 100
        - asset: assets/fonts/Inter-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/Inter-Light.ttf
          weight: 300
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Inter-Black.ttf
          weight: 900
        - asset: assets/fonts/Inter-Italic.ttf
          style: italic
        - asset: assets/fonts/Inter-BoldItalic.ttf
          weight: 700
          style: italic
