// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe473oQM-gyLQGnRT0CYmnjVMHrsPJPmw',
    appId: '1:978160887844:web:479a75ed76db00bcee90b1',
    messagingSenderId: '978160887844',
    projectId: 'easy-vat-v2',
    authDomain: 'easy-vat-v2.firebaseapp.com',
    storageBucket: 'easy-vat-v2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB319Kp3TrdGC8RMwQMmjW24zfRYYxddAs',
    appId: '1:978160887844:android:aacc8408e26f0b8fee90b1',
    messagingSenderId: '978160887844',
    projectId: 'easy-vat-v2',
    storageBucket: 'easy-vat-v2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxOdkxPafIkSRLAcwfNcd0A1HI3mliJn8',
    appId: '1:978160887844:ios:1f180c0466d8d6afee90b1',
    messagingSenderId: '978160887844',
    projectId: 'easy-vat-v2',
    storageBucket: 'easy-vat-v2.firebasestorage.app',
    iosBundleId: 'com.example.easyVatV2',
  );
}
